apiVersion: v1
kind: Service
metadata:
  name: llm-serving
spec:
  selector:
    app: llm-serving
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  - protocol: TCP
    port: 8001
    targetPort: 8001
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer